const SUCCESS = 200;
const USER_DATA_INCOMPLETE = 301;
const INVALID_USER_EMAIL = 302;
const USER_EXIST_ERROR = 303;
const CAN_NOT_UPDATE_USER_ERROR = 304;
const NO_USER_WITH_ID_ERROR = 305;
const WRONG_PERMISSION_NAME_ERROR = 306;
const CAN_NOT_ADD_PERMISSION_ERROR = 307;
const CAN_NOT_EDIT_PERMISSION_ERROR = 308;
const CAN_NOT_DELETE_PERMISSION_ERROR = 309;
const AUTHENTICATION_ERROR = 401;
const LOGIN_ERROR = 402;
const PERMISSION_ERROR = 403;
const NOT_FOUND = 404;
const TYPE_ERROR = 405;
const VALIDATION_ERROR = 422;
const SERVER_ERROR = 500;
const DATABASE_QUERY_ERROR = 501;
const DUBLICATE_KEY = 11000;
module.exports = {
    SERVER_ERROR,
    VALIDATION_ERROR,
    AUTHENTICATION_ERROR,
    SUCCESS, 
    NOT_FOUND,
    DUBLICATE_KEY,
    TYPE_ERROR,
    LOGIN_ERROR,
    DATABASE_QUERY_ERROR,
    PERMISSION_ERROR,
    USER_DATA_INCOMPLETE,
    INVALID_USER_EMAIL,
    USER_EXIST_ERROR,
    CAN_NOT_UPDATE_USER_ERROR,
    NO_USER_WITH_ID_ERROR,
    WRONG_PERMISSION_NAME_ERROR,
    CAN_NOT_ADD_PERMISSION_ERROR,
    CAN_NOT_EDIT_PERMISSION_ERROR,
    CAN_NOT_DELETE_PERMISSION_ERROR
}